version: "3.9"

services:
  web:
    # build: .
    image: sajeyks/hello-world:v1
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:13
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "NAME =postgres"
      - "USER =postgres"
      - "PASSWORD =pstSQL254"
      - "HOST =db"
      - "PORT =5432"


volumes:
  postgres_data: